repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: safety-scope
        name: safety-scope
        entry: scripts/precommit-safety.sh
        language: system
        pass_filenames: false
        stages: [commit]
