site_name: Ethical Hacking Learners Course
site_url: https://gwizard98.github.io/ethical-hacking-course/
repo_url: https://github.com/GWizard98/ethical-hacking-course
repo_name: ethical-hacking-course
docs_dir: .
use_directory_urls: true
# Privacy-friendly analytics (optional): add Plausible if desired
# extra:
#   analytics:
#     provider: plausible
#     domain: gwizard98.github.io
#     src: https://plausible.io/js/plausible.js

theme:
  name: material
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        es: Español
extra_javascript:
  - docs/assets/js/quiz.js
extra:
  analytics:
    provider: plausible
    domain: gwizard98.github.io
    src: https://plausible.io/js/plausible.js
nav:
  - Start here: docs/start-here.md
  - Progress Tracker: docs/progress/progress-template.md
  - Home: README.md
  - Outline: docs/outline.md
  - Lab Setup: docs/lab-setup.md
  - Guided Lab: docs/labs/juice-shop-walkthrough.md
  - NICE Mapping: docs/frameworks/nice-mapping.md
  - ATT&CK Matrix: docs/frameworks/attack-matrix.md
  - Detections: docs/detections/sigma-example.yml
  - SIEM Lab: docs/labs/siem.md
  - Modules:
      - 00 — Introduction: modules/00-introduction/README.md
      - 01 — Operating Systems: modules/01-operating-systems/README.md
      - 02 — Networking Essentials: modules/02-networking/README.md
      - 03 — Legal & Ethics: modules/03-legal-ethics/README.md
      - 04 — Linux Tools: modules/04-linux-tools/README.md
      - 05 — Scripting: modules/05-scripting-python/README.md
      - 06 — Web Security: modules/06-web-security-fundamentals/README.md
      - 07 — Network Security: modules/07-network-security-fundamentals/README.md
      - 08 — Threat Modeling: modules/08-threat-modeling-risk/README.md
      - 09 — Vulnerability Assessment: modules/09-vulnerability-assessment/README.md
      - 10 — CTF & Labs: modules/10-ctf-and-labs/README.md
      - 11 — Defensive Basics: modules/11-defensive-security-basics/README.md
      - 12 — Career & Learning: modules/12-career-continued-learning/README.md
      - 13 — Capstone: modules/13-capstone/README.md
      - 14 — Windows Fundamentals: modules/14-windows-fundamentals/README.md
      - 15 — Web Testing Methodology: modules/15-web-app-testing-methodology/README.md
      - 16 — Secure Coding & Review: modules/16-secure-coding-and-code-review/README.md
      - 17 — Cloud Security Fundamentals: modules/17-cloud-security-fundamentals/README.md
      - 18 — Advanced Threat Modeling: modules/18-advanced-threat-modeling/README.md
      - 19 — Adversary Simulation Basics: modules/19-adversary-simulation-basics/README.md
      - 20 — Detection Engineering: modules/20-detection-engineering/README.md
      - 21 — Free Practice: Web Ops: modules/21-free-practice-web/README.md
      - 22 — Free Practice: Network Ops: modules/22-free-practice-network/README.md
      - 23 — Free Practice: Blue-Team: modules/23-free-practice-blue-team/README.md
  - Lab VM: docs/lab-vm.md
  - Assessments: docs/assessments/quiz-bank.md
  - Instructor: docs/instructor/keys.md
  - Feedback: docs/feedback.md
  - Quizzes:
      - Networking: docs/quizzes/networking.md
